#! /usr/bin/env python3

from os import chdir
from os.path import dirname
from pathlib import Path
from subprocess import run
import sys


def main():
    
    script_path = Path(dirname(Path(sys.argv[0]).resolve()))
    classpath1 = script_path / "qualimap.jar"
    classpath2 = script_path / "lib/*"
    classpath = str(classpath1) + ":" + str(classpath2)
    
    run([
            "java",
            "-cp", classpath,
            "org.bioinfo.ngs.qc.qualimap.main.NgsSmartMain"
        ] +
        sys.argv[1:])


if __name__ == "__main__":
    main()
